# Generated by Django 5.2.5 on 2025-10-16 02:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_type', models.CharField(choices=[('MRI_BRAIN', 'MRI Brain'), ('MRI_SPINE', 'MRI Spine'), ('MRI_KNEE', 'MRI Knee'), ('MRI_SHOULDER', 'MRI Shoulder'), ('MRI_ABDOMEN', 'MRI Abdomen'), ('CT_HEAD', 'CT Head'), ('CT_ABDOMEN', 'CT Abdomen'), ('CT_CHEST', 'CT Chest'), ('XRAY_CHEST', 'X-Ray Chest'), ('XRAY_SPINE', 'X-Ray Spine')], max_length=20)),
                ('modality', models.CharField(choices=[('MRI', 'MRI'), ('CT', 'CT'), ('XRAY', 'X-Ray')], max_length=10)),
                ('wait_time', models.IntegerField(help_text='Wait time in minutes')),
                ('scan_duration', models.IntegerField(help_text='Actual scan time in minutes')),
                ('satisfaction_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Patient satisfaction score (1-5)')),
                ('is_emergency', models.BooleanField(default=False)),
                ('referring_physician', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Patient Visit',
                'verbose_name_plural': 'Patients Visits',
                'ordering': ['-visit_date'],
            },
        ),
    ]
