# Generated by Django 5.2.5 on 2025-10-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientsVisits',
            new_name='PatientVisits',
        ),
    ]
