# Generated by Django 5.2.5 on 2025-10-29 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_rename_patientsvisits_patientvisits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientVisits',
            new_name='PatientVisit',
        ),
    ]
